# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  tag: $(Build.BuildId)

stages:

- stage: Build_and_Push_Image
  displayName: Build & Push Stage
  jobs:
  - job: Build
    displayName: Build & Push Job
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub_svc_connection'
        repository: 'athithyanac/ADO-currency-exchange'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag),latest'