# Build and Push Docker using 2 stages
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  tag: $(Build.BuildId)

stages:

- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build Job
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub_svc_connection'
        repository: 'athithyanac/$(Build.SourceBranchName)_$(Build.Repository.Name)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

    - script: |
        docker save 'athithyanac/$(Build.SourceBranchName)_$(Build.Repository.Name)':$(tag) -o image.tar
      displayName: Save Docker Image as tar file

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'image.tar'
        artifact: 'docker-image'

- stage: Push
  jobs:
  - job: Push
    displayName: Push Job
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'docker-image'
        targetPath: '.'

    - script: |
        docker load -i image.tar
      displayName: Load Docker Image from file


    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub_svc_connection'
        repository: 'athithyanac/$(Build.SourceBranchName)_$(Build.Repository.Name)'
        command: 'push'
        tags: $(tag)
